# Generated by Django 4.2.4 on 2023-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('email_tutor', models.EmailField(max_length=254)),
                ('telefono_tutor', models.PositiveIntegerField()),
                ('curso_interes', models.CharField(choices=[('Jardin', 'Jardín de Infantes'), ('Educacion', 'Educación Primaria'), ('Secundaria', 'Educación Secundaria')], max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
